service: django-lambda

params:
  staging:
    DOCKERFILE: Dockerfile.staging
  prod:
    DOCKERFILE: Dockerfile.production

custom:
  prune:
    automatic: true
    number: 3

provider:
  name: aws
  region: us-east-1
  stage: staging
  deploymentBucket: django-lambda-function-url-${self:provider.stage}
  ecr:
    images:
      django_lambda:
        path: "."
        file: ${param:DOCKERFILE}

functions:
  - app:
      image: django_lambda
      memorySize: 256
      timeout: 900
      url:
        cors: true
      vpc:
        securityGroupIds:
          - sg-01bd8270368fa88a4
        subnetIds:
          - subnet-067cc5f43fd51d979

package:
  individually: true

plugins:
  - serverless-prune-plugin
