service: django-lambda

params:
  staging:
    DOCKERFILE: Dockerfile.staging
  prod:
    DOCKERFILE: Dockerfile.production

custom:
  prune:
    automatic: true
    number: 3

provider:
  name: aws
  region: us-east-1
  stage: staging
  logRetentionInDays: 3
  ecr:
    images:
      django_lambda:
        path: "."
        file: ${param:DOCKERFILE}
  environment:
    DEBUG: 0

functions:
  - app:
      image: django_lambda
      memorySize: 256
      timeout: 900
      url:
        cors: true

package:
  individually: true

plugins:
  - serverless-prune-plugin
