Resources:
  SubscriptionAlarmEmail:
    Type: AWS::SNS::Subscription
    Condition: IsProduction
    Properties:
      Protocol: email
      Endpoint: ${env:DJANGO_SUPERUSER_EMAIL, ''}
      TopicArn: !Ref TopicAlertAlarmsDjangoLambda
