name: pipeline

on:
  push:
    branches:
      - staging
      - master

permissions:
  id-token: write
  contents: read

jobs:
  set_stage:
    runs-on: ubuntu-latest
    outputs:
      stage: ${{ steps.set_stage.outputs.stage }}
    steps:
      - name: Set Stage Environment Variable
        id: set_stage
        run: |
          if [[ $GITHUB_REF == "refs/heads/master" ]]; then
            echo "stage=production" >> $GITHUB_OUTPUT
          else
            echo "stage=staging" >> $GITHUB_OUTPUT
          fi

  deploy:
    needs: set_stage
    runs-on: ubuntu-latest
    environment: ${{needs.set_stage.outputs.stage}}
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE }}
          aws-region: ${{ secrets.REGION || 'us-east-1' }}

      - name: Set Environment Variables for ${{ needs.set_stage.outputs.stage }}
        run: |
          printf 'DJANGO_SECRET_KEY="%s"\n' "${{ secrets.DJANGO_SECRET_KEY }}" >> .env.${{ needs.set_stage.outputs.stage }}
          printf 'DJANGO_SUPERUSER_USERNAME="%s"\n' "${{ secrets.DJANGO_SUPERUSER_USERNAME }}" >> .env.${{ needs.set_stage.outputs.stage }}
          printf 'DJANGO_SUPERUSER_PASSWORD="%s"\n' "${{ secrets.DJANGO_SUPERUSER_PASSWORD }}" >> .env.${{ needs.set_stage.outputs.stage }}
          printf 'AWS_S3_ACCESS_KEY="%s"\n' "${{ secrets.AWS_S3_ACCESS_KEY }}" >> .env.${{ needs.set_stage.outputs.stage }}
          printf 'AWS_S3_ACCESS_SECRET="%s"\n' "${{ secrets.AWS_S3_ACCESS_SECRET }}" >> .env.${{ needs.set_stage.outputs.stage }}

          if [ "${{ needs.set_stage.outputs.stage }}" == "staging" ]; then
            printf 'AWS_S3_BUCKET_DB="%s"\n' "${{ secrets.AWS_S3_BUCKET_DB }}" >> .env.${{ needs.set_stage.outputs.stage }}
          fi

          if [ "${{ needs.set_stage.outputs.stage }}" == "production" ]; then
            printf 'DJANGO_SUPERUSER_EMAIL="%s"\n' "${{ secrets.DJANGO_SUPERUSER_EMAIL }}" >> .env.${{ needs.set_stage.outputs.stage }}
            printf 'AWS_S3_BUCKET_STORAGE="%s"\n' "${{ secrets.AWS_S3_BUCKET_STORAGE }}" >> .env.${{ needs.set_stage.outputs.stage }}
            printf 'RDS_MYSQL_DB_HOST="%s"\n' "${{ secrets.RDS_MYSQL_DB_HOST }}" >> .env.${{ needs.set_stage.outputs.stage }}
            printf 'RDS_MYSQL_DB_NAME="%s"\n' "${{ secrets.RDS_MYSQL_DB_NAME }}" >> .env.${{ needs.set_stage.outputs.stage }}
            printf 'RDS_MYSQL_DB_USER="%s"\n' "${{ secrets.RDS_MYSQL_DB_USER }}" >> .env.${{ needs.set_stage.outputs.stage }}
            printf 'RDS_MYSQL_DB_PASSWORD="%s"\n' "${{ secrets.RDS_MYSQL_DB_PASSWORD }}" >> .env.${{ needs.set_stage.outputs.stage }}
          fi

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 20.x

      - name: Install Dependencies
        run: npm install

      - name: Load Environment Variables
        run: |
          while IFS= read -r line; do
            if [[ ! "$line" =~ ^#.* && -n "$line" ]]; then
              export "$line"
            fi
          done < .env.${{needs.set_stage.outputs.stage}}

      - name: Serverless Deploy
        run: npx sls deploy -s ${{needs.set_stage.outputs.stage}}
