name: pipeline
on:
  workflow_dispatch:
    inputs:
      stage:
        description: "Stage"
        type: choice
        options:
          - staging
          - production
permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    name: Deploy ${{ github.event.inputs.stage }}
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.stage }}
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE }}
          aws-region: ${{ secrets.REGION || 'us-east-1' }}

      - name: Set Environment Variables for ${{ github.event.inputs.stage }}
        run: |
          echo "DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" >> .env.${{ github.event.inputs.stage }}
          echo "DJANGO_SUPERUSER_USERNAME=${{ secrets.DJANGO_SUPERUSER_USERNAME }}" >> .env.${{ github.event.inputs.stage }}
          echo "DJANGO_SUPERUSER_PASSWORD=${{ secrets.DJANGO_SUPERUSER_PASSWORD }}" >> .env.${{ github.event.inputs.stage }}
          echo "AWS_S3_ACCESS_KEY=${{ secrets.AWS_S3_ACCESS_KEY }}" >> .env.${{ github.event.inputs.stage }}
          echo "AWS_S3_ACCESS_SECRET=${{ secrets.AWS_S3_ACCESS_SECRET }}" >> .env.${{ github.event.inputs.stage }}

          if [ "${{ github.event.inputs.stage }}" == "staging" ]; then
            echo "AWS_S3_BUCKET_DB=${{ secrets.AWS_S3_BUCKET_DB }}" >> .env.${{ github.event.inputs.stage }}
          fi

          if [ "${{ github.event.inputs.stage }}" == "production" ]; then
            echo "DJANGO_SUPERUSER_EMAIL=${{ secrets.DJANGO_SUPERUSER_EMAIL }}" >> .env.${{ github.event.inputs.stage }}
            echo "AWS_S3_BUCKET_STORAGE=${{ secrets.AWS_S3_BUCKET_STORAGE }}" >> .env.${{ github.event.inputs.stage }}
            echo "RDS_MYSQL_DB_HOST=${{ secrets.RDS_MYSQL_DB_HOST }}" >> .env.${{ github.event.inputs.stage }}
            echo "RDS_MYSQL_DB_NAME=${{ secrets.RDS_MYSQL_DB_NAME }}" >> .env.${{ github.event.inputs.stage }}
            echo "RDS_MYSQL_DB_USER=${{ secrets.RDS_MYSQL_DB_USER }}" >> .env.${{ github.event.inputs.stage }}
            echo "RDS_MYSQL_DB_PASSWORD=${{ secrets.RDS_MYSQL_DB_PASSWORD }}" >> .env.${{ github.event.inputs.stage }}
          fi

      - name: Debug .env file content
        run: cat .env.${{ github.event.inputs.stage }}

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 20.x

      - name: Install Dependencies
        run: npm install

      - name: Load Environment Variables
        run: |
          set -o allexport
          source .env.${{ github.event.inputs.stage }}
          set +o allexport

      - name: Serverless Deploy
        run: npx sls deploy -s ${{ github.event.inputs.stage }}
